quarkus.application.name=pw

# Banco de dados local da barbearia.
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=postgres
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:8082/barbearia
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/barbearia

# Em desenvolvimento, mantem as tabelas sincronizadas com as entidades.
#quarkus.hibernate-orm.database.generation=update
# Define o tipo e as credenciais do seu banco real


# Aponta para o seu banco real (Isso desativa o banco embutido do Quarkus)
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/barbearia

# Cria as tabelas automaticamente
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.db-version=14.15.0
###quarkus.embedded.postgresql.data.dir=C:/emdedpg
quarkus.embedded.postgresql.data.dir=C:/Postgres
quarkus.embedded.postgresql.port=8082

quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.default-schema=public

#JWT - Chave usada para assinar e validar os token
mp.jwt.verify.issuer=https://barbearia.ifg.br

mp.jwt.verify.publickey.location=publickey.pem
smallrye.jwt.sign.key.location=privateKey.pem