quarkus.application.name=pw-barbearia

# Banco de dados local da barbearia.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:8082/barbearia

# Em desenvolvimento, mantem as tabelas sincronizadas com as entidades.
quarkus.hibernate-orm.database.generation=update
